### PR TITLE
Added ScanCentral integration for Azure, AWS and GCP

### PR DESCRIPTION
**Pull request by rohitbaryha1**
Added Azure DevOps, AWS CodeStar and GCP CloudBuild support for Fortify ScanCentral SAST & DAST.

### CODE REVIEW

**Comment by dylanbthomas** [comment]
@rohitbaryha1 A couple points of feedback:

For GCP, can you please adjust the cloudbuild.yaml file to reference the various other yaml files in the devops/gcp folder (like with AWS)?  Similarly, we should move the FortifyScanCommands batch file to the gcp folder as well.

For AWS, is there a reason the SAST files are bash vs sh for DAST?  Can we make these consistent?

**Comment by rohitbaryha1** [comment]
@dylanbthomas unfortunately, GCP default implementation does not support multiple/nested yaml files (like GitLab does). currently cloudbuild.yaml file contains SAST and DAST functionality both for the app, the YAML files in the DevOps-integration folder are a break-up of SAST and DAST separate functionality if anyone would like to use one or the other. I see two options here:

option 1: delete the cloudbuild.yaml file and keep other files like it used to. [[preferable]]
option 2: delete the devops-integration file for GCP and cloudbuild.yaml will have all the full functionality like TRAVISCI.. 

FortifyScanCommands.bat file is just a small utility to generate FPR file and has nothing to do with the integration, I could delete the file

AWS, will change for BASH to keep consistent.

**Comment by dylanbthomas** [comment]
@rohitbaryha1 Thanks for the details.  Let's keep it as-is with the main cloudbuild.yaml file demonstrating how to do SAST+DAST with ScanCentral.  We should also leave the individual examples in the /devops folder, and can you please add a comment that directs users to review /devops-integrations/gcp/cloudbuild_fortify_sast_fod.yaml as a reference template for integration with Fortify on Demand please?

Let's delete the fpr/.bat file if it's not needed to avoid confusion.

**Comment by rohitbaryha1** [comment]
Thanks @dylanbthomas, I have incorporated the review comments and check-in the code.
GCP will stay as is, BATCH file is deleted and AWS script aligned with BASH script

**Review by dylanbthomas — APPROVED** [review]

**Pull request merged**
